### ISSUE TITLE
icons not properly sizing

### ISSUE THREAD

**Issue by vdegenne** [VandeurenGlenn/rollup-plugin-material-symbols#7]
![image](https://github.com/VandeurenGlenn/rollup-plugin-material-symbols/assets/2827383/b782bd3d-dc15-469d-84a9-6930aac34c15)

One solution would be to remove `width` and `height` attribute from the svg before replacing content and use `style="width:100%;height:100%`  instead.

MW components are forcing the layout of slotted content so it should work fine, just need to fit to parent size.

**Comment by VandeurenGlenn** [comment]
I'll see what's going on

**Comment by VandeurenGlenn** [comment]
see [material-web/#4640](https://github.com/material-components/material-web/pull/4640)

**Comment by VandeurenGlenn** [comment]
closed https://github.com/material-components/material-web/issues/4639
